excluded:
  - Packages/ViviraDesignSystem/.build
  - Packages/ViviraDesignSystem/Sources/ViviraDesignSystem/generated

type_name:
  min_length: 1

identifier_name:
  min_length: 1

nesting:
  type_level: 2
